// js/data.js – Central game catalog (relative paths from root)

const GAMES_CATALOG = [
  {
    id: "sts2",
    title: "Slay the Spire II",
    titleWhite: "Slay the",
    titleGradient: "Spire II",
    tags: ["Roguelike", "Deckbuilding", "Strategy", "Card Game"],
    description: "The ultimate roguelike deckbuilder returns. New perils demand sharper strategies. Climb the spire alone or with friends.",
    review: "Overwhelmingly Positive",
    releaseDate: "Mar 6, 2026",
    platforms: ["win", "mac"],
    thumb: "assets/img/games/sts2-thumb.jpg",
    topThumb: "assets/img/games/sts2-thumb.jpg",
    categoryThumb: "assets/img/games/sts2-thumb.jpg",
    gallery: ["assets/img/games/sts2-1.jpg", "assets/img/games/sts2-2.jpg", "assets/img/games/sts2-3.jpg", "assets/img/games/sts2-4.jpg"],
    category: "multi",
    steamLink: "https://store.steampowered.com/app/2868840/",
    developer: "MegaCrit",
    publisher: "MegaCrit",
    rating: 4.5,
    stars: "★★★★☆",
    video: "assets/vid/mp vid/sts2 vid.mp4",
    heroVideo: "assets/vid/hero/STS2.mp4",
    bgImage: "assets/img/games/sts2-cover.jpg",
    duration: 33000
  },
  {
    id: "rdr2",
    title: "Red Dead Redemption 2",
    titleWhite: "Red Dead",
    titleGradient: "Redemption 2",
    tags: ["Action", "Adventure", "Open World", "Western", "Story Rich"],
    description: "America, 1899. The end of the Wild West era has begun. Arthur Morgan and the Van der Linde gang are outlaws on the run.",
    review: "Very Positive",
    releaseDate: "Oct 26, 2018",
    platforms: ["win", "ps", "xbox"],
    thumb: "assets/img/games/rdr2-thumb.jpg",
    topThumb: "assets/img/games/rdr2-thumb.jpg",
    categoryThumb: "assets/img/games/rdr2-thumb.jpg",
    gallery: ["assets/img/games/rdr2-1.jpg", "assets/img/games/rdr2-2.jpg", "assets/img/games/rdr2-3.jpg", "assets/img/games/rdr2-4.jpg"],
    category: "single",
    steamLink: "https://store.steampowered.com/app/1174180/",
    developer: "Rockstar Games",
    publisher: "Rockstar Games",
    rating: 4.6,
    stars: "★★★★☆",
    video: "assets/vid/sp vid/rdr2 vid.mp4",
    heroVideo: "assets/vid/hero/RDR2.mp4",
    bgImage: "assets/img/games/rdr2-cover.jpg",
    duration: 24000
  },
  {
    id: "stardew",
    title: "Stardew Valley",
    titleWhite: "Stardew",
    titleGradient: "Valley",
    tags: ["RPG", "Simulation", "Cozy", "Farming", "Sandbox"],
    description: "Inherited an old farm plot. Turn overgrown fields into a thriving home. Grow crops, raise animals, fish, mine, and build relationships.",
    review: "Overwhelmingly Positive",
    releaseDate: "Feb 26, 2016",
    platforms: ["win", "mac", "ns", "ps", "xbox"],
    thumb: "assets/img/games/sv-thumb.jpg",
    topThumb: "assets/img/sp img/sv cover.jpg",
    categoryThumb: "assets/img/sp img/sv cover.jpg",
    gallery: ["assets/img/games/sv-1.jpg", "assets/img/games/sv-2.jpg", "assets/img/games/sv-3.jpg", "assets/img/games/sv-4.jpg"],
    category: "single",
    steamLink: "https://store.steampowered.com/app/413150/",
    developer: "ConcernedApe",
    publisher: "ConcernedApe",
    rating: 4.9,
    stars: "★★★★★",
    video: "assets/vid/sp vid/sv vid.mp4",
    heroVideo: "assets/vid/hero/SV.mp4",
    bgImage: "assets/img/games/sv-cover.jpg",
    duration: 35000
  },
  {
    id: "itt",
    title: "It Takes Two",
    titleWhite: "It Takes",
    titleGradient: "Two",
    tags: ["Action", "Co-op", "Adventure", "Platformer", "Funny"],
    description: "A fun emotional co‑op adventure. Cody and May, turned into tiny dolls, must work together to mend their relationship.",
    review: "Overwhelmingly Positive",
    releaseDate: "Mar 26, 2021",
    platforms: ["win", "ns", "ps", "xbox"],
    thumb: "assets/img/games/itt-thumb.jpg",
    topThumb: "assets/img/games/itt-thumb.jpg",
    categoryThumb: "assets/img/games/itt-thumb.jpg",
    gallery: ["assets/img/games/itt-1.jpg", "assets/img/games/itt-2.jpg", "assets/img/games/itt-3.jpg", "assets/img/games/itt-4.jpg"],
    category: "multi",
    steamLink: "https://store.steampowered.com/app/1426210/",
    developer: "Hazelight Studios",
    publisher: "Electronic Arts",
    rating: 4.8,
    stars: "★★★★★",
    video: "assets/vid/mp vid/itt vid.mp4",
    heroVideo: "assets/vid/hero/ITT.mp4",
    bgImage: "assets/img/games/itt-cover.jpg",
    duration: 38000
  },
  {
    id: "graveyard",
    title: "Graveyard Keeper",
    titleWhite: "Graveyard",
    titleGradient: "Keeper",
    tags: ["RPG", "Simulation", "Dark Humor", "Crafting", "Management"],
    description: "Build and manage a medieval graveyard while facing ethical dilemmas. Bury bodies, craft items, and deal with quirky villagers.",
    review: "Very Positive",
    releaseDate: "Aug 15, 2018",
    platforms: ["win", "mac", "ns", "ps", "xbox"],
    thumb: "assets/img/games/gk-thumb.jpg",
    topThumb: "assets/img/games/gk-thumb.jpg",
    categoryThumb: "assets/img/games/gk-thumb.jpg",
    gallery: ["assets/img/games/gk-1.jpg", "assets/img/games/gk-2.jpg", "assets/img/games/gk-3.jpg", "assets/img/games/gk-4.jpg"],
    category: "single",
    steamLink: "https://store.steampowered.com/app/599140/",
    developer: "Lazy Bear Games",
    publisher: "tinyBuild",
    rating: 4.3,
    stars: "★★★★☆",
    video: "assets/vid/sp vid/gk vid.mp4",
    heroVideo: "assets/vid/hero/GK.mp4",
    bgImage: "assets/img/games/gk-thumb.jpg",
    duration: 30000
  },
  {
    id: "alittle",
    title: "A Little to the Left",
    titleWhite: "A Little to",
    titleGradient: "the Left",
    tags: ["Puzzle", "Cozy", "Casual", "Relaxing"],
    description: "Sort, stack, and organize household items. Watch out for a mischievous cat! A tidy puzzle game with multiple solutions.",
    review: "Very Positive",
    releaseDate: "Nov 8, 2022",
    platforms: ["win", "mac", "ns", "ps", "xbox"],
    thumb: "assets/img/games/alttl-thumb.jpg",
    topThumb: "assets/img/games/alttl-thumb.jpg",
    categoryThumb: "assets/img/games/alttl-thumb.jpg",
    gallery: ["assets/img/games/alttl-1.png", "assets/img/games/alttl-2.png", "assets/img/games/alttl-3.jpg", "assets/img/games/alttl-4.jpg"],
    category: "single",
    steamLink: "https://store.steampowered.com/app/1629520/",
    developer: "Max Inferno",
    publisher: "Secret Mode",
    rating: 4.0,
    stars: "★★★★☆",
    video: "assets/vid/sp vid/alttl vid.mp4",
    heroVideo: "assets/vid/hero/ALTTL.mp4",
    bgImage: "assets/img/games/alttl-cover.jpg",
    duration: 31000
  },
  {
    id: "picopark",
    title: "Pico Park",
    titleWhite: "Pico",
    titleGradient: "Park",
    tags: ["Co-op", "Puzzle", "Cute", "Party"],
    description: "Work together with friends to solve puzzles in this charming cooperative game. Teamwork is key!",
    review: "Very Positive",
    releaseDate: "May 7, 2021",
    platforms: ["win", "mac", "ns", "ps", "xbox"],
    thumb: "assets/img/games/pp-thumb.jpg",
    topThumb: "assets/img/mp img/pp cover.jpg",
    categoryThumb: "assets/img/mp img/ppcover.jpg",
    gallery: ["assets/img/games/pp-1.jpg", "assets/img/games/pp-2.jpg", "assets/img/games/pp-3.jpg", "assets/img/games/pp-4.jpg"],
    category: "multi",
    steamLink: "https://store.steampowered.com/app/1509960/",
    developer: "TECOPARK",
    publisher: "TECOPARK",
    rating: 4.5,
    stars: "★★★★☆",
    video: "assets/vid/mp vid/pp vid.mp4",
    heroVideo: "assets/vid/hero/PP.mp4",
    bgImage: "assets/img/mp img/ppcover.jpg",
    duration: 38000
  },
  {
    id: "cod",
    title: "Call of Duty: Black Ops III",
    titleWhite: "Call of Duty:",
    titleGradient: "Black Ops III",
    tags: ["Action", "FPS", "Zombies", "Multiplayer", "Co-op"],
    description: "A dark, twisted future where lines blur between humanity and military robotics. Wall‑run, slide, and fight in 2065.",
    review: "Very Positive",
    releaseDate: "Nov 6, 2015",
    platforms: ["win", "ps", "xbox"],
    thumb: "assets/img/games/bo3-thumb.jpg",
    topThumb: "assets/img/games/bo3-thumb.jpg",
    categoryThumb: "assets/img/games/bo3-thumb.jpg",
    gallery: ["assets/img/games/bo3-1.jpg", "assets/img/games/bo3-2.jpg", "assets/img/games/bo3-3.jpg", "assets/img/games/bo3-4.jpg"],
    category: "multi",
    steamLink: "https://store.steampowered.com/app/311210/",
    developer: "Treyarch",
    publisher: "Activision",
    rating: 4.7,
    stars: "★★★★☆",
    video: "assets/vid/mp vid/cod vid.mp4",
    heroVideo: "assets/vid/hero/BO3.mp4",
    bgImage: "assets/img/games/bo3-cover.jpg",
    duration: 38000
  }
];

const TOP_RATED_GAMES = ["sts2", "alittle", "cod"];